####################################
# Browser Configuration : chrome or firefox
####################################
browser=firefox
headless=false
environment=qa

####################################
# Execution Configuration : local or grid or browserstack or selenoid-grid
####################################
execution=local
grid.url=http://localhost:4444

####################################
# Application URLs
####################################
erail.url=https://erail.in/
orangehrm.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
google.url=https://www.google.com/

####################################
# Timeouts
####################################
explicit.wait=30
page.load.timeout=60

####################################
# Test Data
####################################
expected.station.file=src/main/resources/data/ExpectedStations.xlsx
login.data.file=src/main/resources/data/LoginData.xlsx

####################################