####################################
# Browser Configuration : chrome or firefox
####################################
browser=firefox
headless=false
environment=qa

####################################
# Execution Configuration : local or grid or browserstack or selenoid-grid
####################################
execution=local
grid.url=http://localhost:4444

####################################
# Application URLs
####################################
erail.url=https://erail.in/
orangehrm.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
google.url=https://www.google.com/
shadowdom.url=https://practice.expandtesting.com/shadowdom

####################################
# Timeouts
####################################
explicit.wait=30
page.load.timeout=5

####################################
# Retry Count
####################################
retry.count=2

####################################
# Test Data
####################################
expected.station.file=src/main/resources/data/ExpectedStations.xlsx
login.data.file=src/main/resources/data/LoginData.xlsx

##################################
# API Configuration
##################################

api.base.url=https://api.spotify.com/v1/

api.connect.timeout=30000

api.read.timeout=30000

api.content.type=application/json

api.accept=application/json

api.log.request=true

api.log.response=true

api.key=free_user_3HGkuT8B8ivujOjkL8wblw0Mqg1

############################################
# Spotify OAuth Configuration
############################################

spotify.client.id=277ff8e6e1824517af0990fdd8a6801b

spotify.client.secret=d181e124c4a04967ade547d601d12b19

spotify.redirect.uri=http://127.0.0.1:8888/callback

spotify.authorization.url=https://accounts.spotify.com/authorize

spotify.token.url=https://accounts.spotify.com/api/token

spotify.scopes=playlist-read-private playlist-read-collaborative playlist-modify-private playlist-modify-public

spotify.authorization.code=AQBrq2txhyrlQzLGWXtdxABEY18RjYZQUl7zh1GnEJI2OFFw-_TNeyGc-6H4XT2FPxfvpkjdriRNOLJF18iREYVRPLhJlrVR9CcLXu-oNbosiL7mok2RlhTlAZhB9T9dYNpVyIfiTHcULfdmrnfvvbnKWVpCmWFroK2PdNGAzU-4viobrnnxmZ7Dp_IF5sTZZFQODonFIkJuaqcIFEX3IBjXyjLYWvtghxZH8zgkt34TwCGBWxjdnVBnpuvg2EBo1HxcCV6-DFKs2dPIH9Rsv1yglmOBBRfKvqUDFWbRrqboszX7YOSqVHsFARulrTvQaT_8ib0P9RI2IJ4fr4PQauIbOw_7Te2AckEIx29_
spotify.access.token=

spotify.refresh.token=

############################################
# OAuth Token Store
############################################

oauth.token.store.type=JSON

oauth.token.store.path=oauth/token.json

####################################
