####################################
# Browser Configuration : chrome or firefox
####################################
browser=firefox
headless=false
environment=qa

####################################
# Execution Configuration : local or grid or browserstack or selenoid-grid
####################################
execution=local
grid.url=http://localhost:4444

####################################
# Application URLs
####################################
erail.url=https://erail.in/
orangehrm.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
google.url=https://www.google.com/
shadowdom.url=https://practice.expandtesting.com/shadowdom

####################################
# Timeouts
####################################
explicit.wait=30
page.load.timeout=5

####################################
# Retry Count
####################################
retry.count=2

####################################
# Test Data
####################################
expected.station.file=src/main/resources/data/ExpectedStations.xlsx
login.data.file=src/main/resources/data/LoginData.xlsx

##################################
# API Configuration
##################################

api.base.url=https://api.spotify.com/v1/

api.connect.timeout=30000

api.read.timeout=30000

api.content.type=application/json

api.accept=application/json

api.log.request=true

api.log.response=true

api.key=free_user_3HGkuT8B8ivujOjkL8wblw0Mqg1

############################################
# Spotify OAuth Configuration
############################################

spotify.client.id=277ff8e6e1824517af0990fdd8a6801b

spotify.client.secret=d181e124c4a04967ade547d601d12b19

spotify.redirect.uri=http://127.0.0.1:8888/callback

spotify.authorization.url=https://accounts.spotify.com/authorize

spotify.token.url=https://accounts.spotify.com/api/token

spotify.scopes=playlist-read-private playlist-read-collaborative playlist-modify-private playlist-modify-public

spotify.authorization.code=AQAqlqwtm8UI1laciFJ7GNDXUUjTU0SNblZa3ZRhQx_94WE88RO-sdIc8dMela3kUTx-zmw386OVa-JGJkyF8H8-Q_xacyCrXo7CfRzvMjN09R-JLrU16UJGcUJxm3JYKAQsFVJHW2_mFaPmHVGX-tMQUVj5qclZs_srS685RdQDT5V_-4YlTBfpDrV3MGi8gBT7wWelTAI3DqOZIZsBV0p9hDYpRO_49oCy8o-hreBWggZHS25TMw3y7pj7ep0fo_9BQ2Fj2bfOIdV2R9wR659YDFbknp1vQEGbNoaU41A5Mz4JVVc8kVCW_IaRCLFCfhX2AVzBtfzL9jwDt4T6_btmfSBuNQjMtGK2ners
spotify.access.token=

spotify.refresh.token=

####################################